export * from './validateEmail.jsx';
export * from './validatePassword.jsx';
export * from './validateUsername.jsx';
export * from './validateConfirPassword.jsx'
export * from './validateAddress.jsx';
export * from './validateCompany.jsx';
export * from  './validateDpi.jsx';
export * from './validateIncome.jsx'
export * from './validatePhone.jsx'
export * from './validateName.jsx'